name: Release

on:
  release:
    types: [published]

env:
  OUTPUT_DIR: dist

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    name: build (${{ matrix.target }})
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Set up Rust
        run: |
          rustup show
          rustup target add ${{ matrix.target }}

      - name: Manage Rust cache
        uses: Swatinem/rust-cache@v2.8.1

      - name: Build binary
        id: build
        run: |
          cargo build --verbose --release --target ${{ matrix.target }}

          mkdir ${{ env.OUTPUT_DIR }}
          binary_path="${{ env.OUTPUT_DIR }}/onepassword-exporter-${{ matrix.target }}"
          mv target/${{ matrix.target }}/release/onepassword-exporter "$binary_path"

          echo "binary-path=${binary_path}" >> $GITHUB_OUTPUT

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v5
        with:
          name: dist-${{ matrix.target }}
          path: ${{ steps.build.outputs.binary-path }}

  release:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Download binary artifacts
        uses: actions/download-artifact@v6
        with:
          path: ${{ env.OUTPUT_DIR }}

      - name: Show artifacts
        run: ls -l --all --recursive dist

      - name: Create release
        uses: softprops/action-gh-release@v2.4.1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          generate_release_notes: true
          files: dist/dist-*/onepassword-exporter-*

  # ... release will create tags and will trigger publish-docker job in publish.yaml
